### ISSUE TITLE
Implement a Salt for PasswordCredential

### ISSUE THREAD

**Issue by thejamespinto** [hello-gem/hello#7]
Our passwords are not currently being salted
This should be done ASAP because it will create backward compatibility issues.

**Comment by stepantubanov** [comment]
You already use BCrypt and it automatically adds salt, see: https://github.com/codahale/bcrypt-ruby/blob/master/lib/bcrypt/password.rb#L46

**Comment by thejamespinto** [comment]
@stepantubanov pretty good point, I had forgotten about that, thanks :+1:
